# Generated by Django 5.2.16 on 2026-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="color",
        ),
        migrations.AddField(
            model_name="subject",
            name="theme",
            field=models.CharField(
                choices=[
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("orange", "Orange"),
                    ("purple", "Purple"),
                    ("red", "Red"),
                ],
                default="blue",
                help_text="Theme name for UI",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Optional icon name (e.g. python, database, django)",
                max_length=50,
            ),
        ),
    ]
