# Generated by Django 5.2.16 on 2026-07-21 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_remove_subject_color_subject_theme_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveBigIntegerField(
                        default=1, help_text="Display order within a subject."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="quiz.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subject", "name"), name="unique_topic_per_subject"
                    ),
                    models.UniqueConstraint(
                        fields=("subject", "slug"), name="unique_topic_slug_per_subject"
                    ),
                ],
            },
        ),
    ]
