# Generated by Django 5.2.16 on 2026-07-22 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_subject_uuid_topic_uuid_alter_subject_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("code_snippet", models.TextField(blank=True)),
                ("explanation", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Choice"),
                            ("multiple", "Multiple Choice"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                ("marks", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["topic", "id"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=500)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="quiz.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["topic"], name="quiz_questi_topic_i_06cf1f_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="quiz_questi_difficu_fde0f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_active"], name="quiz_questi_is_acti_995386_idx"
            ),
        ),
    ]
