# Generated by Django 5.2.16 on 2026-07-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_question_choice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="question",
            name="external_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="choice",
            constraint=models.UniqueConstraint(
                fields=("question", "order"), name="unique_choice_order_per_question"
            ),
        ),
    ]
