# Generated by Django 5.2.16 on 2026-07-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_choice_options_question_external_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"ordering": ["question", "order"]},
        ),
    ]
