# Generated by Django 5.2.16 on 2026-07-27 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_alter_choice_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("total_questions", models.PositiveIntegerField(default=20)),
                ("pass_percentage", models.PositiveSmallIntegerField(default=50)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "topics",
                    models.ManyToManyField(related_name="quizzes", to="quiz.topic"),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
