# Generated by Django 5.2.16 on 2026-08-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_quizattempt_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="randomize_choices",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="randomize_questions",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=30, help_text="Duration in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="pass_percentage",
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="total_questions",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
