# Generated by Django 5.2.16 on 2026-08-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_quiz_randomize_choices_quiz_randomize_questions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="questions",
            field=models.ManyToManyField(related_name="attempts", to="quiz.question"),
        ),
    ]
