# Generated by Django 5.2.16 on 2026-08-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_quizattempt_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
